# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

target 'Ronock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM Alamofire
  pod 'Alamofire', '~> 4.7'
  pod 'SDWebImage', '~> 4.0'
  pod 'IHProgressHUD'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Cards'
  pod 'RealmSwift'
  pod 'PullableSheet'
  pod 'JWTDecode'
  pod 'PMAlertController'
  pod 'UIImageView+Extension'
  pod 'NBBottomSheet'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'AppCenter'
  pod "SelectionDialog"
  pod 'MOLH'
  pod "PagingTableView"
  pod 'SwiftyGif'
  pod 'NotificationBannerSwift'
  pod 'ImageSlideshow'
  pod "ImageSlideshow/Alamofire"
  pod 'SRCountdownTimer'
  pod 'Pageboy'
  pod "SwiftRater"
  pod 'lottie-ios'
  pod 'ScrollingStackContainer'
  pod 'CropViewController'

end
